spring:
  application:
    name: apigatewayserver
server:
  port: 8765
zuul:
  routes:
    usermicro:
      path: /user_micro/**
      serviceId: user_micro
    categorymicro:
      path: /category/**
      serviceId: categorymicro
    productmicro:
      path: /product/**
      serviceId: productmicro
eureka:
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/info
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka/