spring:
  application:
    name: apigatewayserver
server:
  port: 8765
zuul:
  routes:
    usermicro:
      path: /user/**
      serviceId: usermicro
    categorymicro:
      path: /category/**
      serviceId: categorymicro
    productmicro:
      path: /product/**
      serviceId: productmicro
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka/