spring:
  application:
    name: apigatewayserver
server:
  port: 8765
zuul:
  routes:
    usermicro:
      path: /usermicro/**
      serviceId: usermicro
    categorymicro:
      path: /categorymicro/**
      serviceId: categorymicro
    productmicro:
      path: /productmicro/**
      serviceId: productmicro
eureka:
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
    health-check-url-path: /actuator/health
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
